---
title: "Exploratory climate plots"
author: "Sanne Evers"
date: "4/14/2022"
output: pdf_document
params:
  CHELSA_data_location: "data/CHELSA_data.csv"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_knit$set(root.dir = '../')

```

# CHELSA data

```{r, fig.dim=c(10,15), warning=FALSE}
options(tidyverse.quiet = TRUE)
library(tidyverse)

clim <- read.csv(here::here(params$CHELSA_data_location)) %>% 
  filter(locality %in% c("Hk", "Cr", "Ks", "Ru") &
           year > 2000)

ggplot(clim) +
  geom_point(aes(x = month, y = tas, shape = locality), colour = "orange") +
  geom_line(aes(x = month, y = tas, linetype = locality), colour = "orange") +
  facet_wrap(vars(year), ncol = 5) +
  ggtitle("Average temperatures across years")

ggplot(clim) +
  geom_point(aes(x = month, y = pr, shape = locality), colour = "blue") +
  geom_line(aes(x = month, y = pr, linetype = locality), colour = "blue") +
  facet_wrap(vars(year), ncol = 4) + 
  ggtitle("Total precipitation across years")

ggplot(clim) +
  geom_point(aes(x = month, y = pet, shape = locality), colour = "purple") +
  geom_line(aes(x = month, y = pet, linetype = locality), colour = "purple") +
  facet_wrap(vars(year), ncol = 4) +
  ggtitle("Potential evapotranspiration across years")

# ggplot(clim) +
#   geom_point(aes(x = month, y = cmi, shape = locality), colour = "green") +
#   geom_line(aes(x = month, y = cmi, linetype = locality), colour = "green") +
#   facet_wrap(vars(year), ncol = 4) + 
#   ggtitle("Climate moisture index across years")

# ggplot(clim) +
#   geom_point(aes(x = month, y = vpd, shape = locality), colour = "red") +
#   geom_line(aes(x = month, y = vpd, linetype = locality), colour = "red") +
#   facet_wrap(vars(year), ncol = 4) + 
#   ggtitle("Vapor pressure deficit across years")



ggplot(clim) +
  geom_point(aes(x = month, y = tas_scaled, shape = locality), colour = "orange") +
  geom_line(aes(x = month, y = tas_scaled, linetype = locality), colour = "orange") +
  geom_point(aes(x = month, y = pr_scaled, shape = locality), colour = "blue") +
  geom_line(aes(x = month, y = pr_scaled, linetype = locality), colour = "blue") +
  # geom_point(aes(x = month, y = cmi_scaled, shape = locality), colour = "green") +
  # geom_line(aes(x = month, y = cmi_scaled, linetype = locality), colour = "green") +
  geom_point(aes(x = month, y = pet_scaled, shape = locality), colour = "purple") +
  geom_line(aes(x = month, y = pet_scaled, linetype = locality), colour = "purple") +
  # geom_point(aes(x = month, y = vpd_scaled, shape = locality), colour = "red") +
  # geom_line(aes(x = month, y = vpd_scaled, linetype = locality), colour = "red") +
  facet_wrap(vars(year), ncol = 4) +
  ggtitle("Scaled temperatures, precipitation, climate moisture index, pot. evapotr. and vapor pressure deficit across years (Scaled per month)", 
          subtitle = "Orange = tas, blue = precipitation, green = climate moisture index, 
          purple = potential evapotranspiration and red = vapor preasure deficit")

 
  

```

